codecov:
  branch: master
  bot: codecovBot

coverage:
  precision: 4
  round: down
  range: 50...100
  status:
    project:
      default:
        enabled: yes
        target: auto
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
    patch:
      default:
        enabled: yes
        target: 100%
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
    changes:
      default:
        enabled: yes
        if_no_uploads: error
        if_not_found: error
        if_ci_failed: error
  ignore:
    - "Onboarding/src"
comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  behavior: new