os: osx
language: c++

branches:
  only:
    - master

env:
  global:
    - CI_VERBOSE=0

script:
  - mkdir build
  - cd build
  - set -e
  - cmake ..
  - cmake --build .
  - ctest -C Debug
  - set +e
