os: osx
language: c++

branches:
  only:
    - master

env:
  global:
    - CI_VERBOSE=0

install:
  - brew install lcov

script:
  - mkdir build
  - cd build
  - set -e
  - cmake ..
  - cmake --build .
  - ctest -C Debug
  - set +e

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
